services:
  - type: web
    name: telegram-gpt-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: TELEGRAM_TOKEN
        value: TU_TOKEN_DE_TELEGRAM
      - key: OPENAI_API_KEY
        value: TU_API_KEY_DE_OPENAI
