services:
  - type: web
    name: telegram-gpt-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: TELEGRAM_TOKEN
        value:  8317619029:AAEQh3kSbcJAGgw2VAa-N7TBxkJwKtYaKV0
      - key: OPENAI_API_KEY
        value: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
